net.Receive("relayDiscordMessageReceived", function(len)
	local username = net.ReadString()
	local message = net.ReadString()
	local colour = net.ReadColor()
	chat.AddText(Color(166, 157, 237), "[Discord] ", colour, username, Color(255, 255, 255), ": ", message)
end)